services:
  app:
    image: olstephen17/contrans_image
    ports:
      - "8050:8050"
    volumes:
      - .:/contrans2026
    networks:
      - dbnetwork

  postgres:
    image: postgres:18.6
    ports:
      - "5432:5432" # What port does the software want to run on?
    volumes:
      - postgresdata:/var/lib/postgresql/18/docker # Where is the data in the container?
    env_file:
      - .env # What needs to be given to the container for secret credentials/passwords/configurations?
    networks:
      - dbnetwork

  mongo:
    image: mongo:8.3.9
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    env_file:
      - .env
    networks:
      - dbnetwork
  
volumes:
  postgresdata:
  mongodata:

networks:
  dbnetwork: